[package]
name = "cookbook"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = "1.18.1"

[[bin]]
name = "cookbook"
path = "src/main.rs"

[lib]
name = "cookbook"
path = "src/lib.rs"
